### ISSUE TITLE
Klasse User fehlt

### ISSUE THREAD

**Issue by themanwhosold** [themanwhosold/notenrechner#81]
Die Klasse User fehlt, wird aber in den Klassen zur Authentifizierung referenziert.

**Comment by vi-mschreiber** [comment]
https://docs.jboss.org/webbeans/reference/current/en-US/html/example.html

Link zu Webseite wo Schmobi seine Ideen herhat :)

**Comment by vi-mschreiber** [comment]
https://docs.jboss.org/webbeans/spec/PDR/html/architecture.html

Dort wird das gleiche behandelt

**Comment by themanwhosold** [comment]
#91 Problem gelöst
